### PR TITLE
整个活

### PR DESCRIPTION
**Pull request by w1ndys**

### CODE REVIEW

**Comment by erkangkang** [comment]
hahaha




自己
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "erkangkang/erkangkang.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月4日(星期一) 中午11:15
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[erkangkang/erkangkang.github.io] 整个活 (PR #1)



 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/erkangkang/erkangkang.github.io/pull/1
 
Commit Summary
    
45519d2  整个活
  
File Changes 
 
(1 file)
    
     A     1.html     (28)   
  
Patch Links:
    
https://github.com/erkangkang/erkangkang.github.io/pull/1.patch
   
https://github.com/erkangkang/erkangkang.github.io/pull/1.diff

**Comment by W1ndys** [comment]
> hahaha
> 
> 
> 
> 
> 自己
> ***@***.***
> 
> 
> 
> &nbsp;
> 
> 
> 
> 
> ------------------&nbsp;原始邮件&nbsp;------------------
> 发件人:                                                                                                                        "erkangkang/erkangkang.github.io"                                                                                    ***@***.***&gt;;
> 发送时间:&nbsp;2024年3月4日(星期一) 中午11:15
> ***@***.***&gt;;
> ***@***.***&gt;;
> 主题:&nbsp;[erkangkang/erkangkang.github.io] 整个活 (PR #1)
> 
> 
> 
>  
>  
> You can view, comment on, or merge this pull request online at:
>  
> &nbsp; https://github.com/erkangkang/erkangkang.github.io/pull/1
>  
> Commit Summary
>     
> 45519d2  整个活
>   
> File Changes 
>  
> (1 file)
>     
>      A     1.html     (28)   
>   
> Patch Links:
>     
> https://github.com/erkangkang/erkangkang.github.io/pull/1.patch
>    
> https://github.com/erkangkang/erkangkang.github.io/pull/1.diff
>   
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

等会，先别合并（，我觉得应该放在source里

**Comment by w1ndys** [comment]
不对，好像应该放source里（

**Comment by w1ndys** [comment]
不对，静态页面文件，好像不用，不是源码

**Pull request closed without merging**
